server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

---

spring-doc:
      api-docs:
        path: /anal-open-api/api-docs
      swagger-ui:
        filter: 'true'
        urls-primary-name: Anal Service Open Api Swagger
        try-it-out-enabled: 'true'
