server:
  port: ${SERVER_PORT:8083}
  error:
    include-message: always

---

spring-doc:
  api-docs:
    path: /event-open-api/api-docs
  swagger-ui:
    filter: 'true'
    urls-primary-name: Event Service Open Api Swagger
    try-it-out-enabled: 'true'
